apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name}}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name}}
    spec:
      containers:
        - name: {{ .Chart.Name}}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.containerPort}}
          env:
            - name: USER_SERVICE_URL
              value: user-service-app.user.svc.cluster.local
            - name: CONFIG_SERVICE_URL
              value: config-server-app-service.config.svc.cluster.local
            - name: REMOTE_SERVICE_REDIS
              value: redis-0.redis.remote.svc.cluster.local

